version: "3.8"

services:
  itinerary-service:
    image: musafirgo2025/itinerary-service:latest
    container_name: itinerary-service
    ports:
      - "8080:8080"
    networks:
      - musafirgo-net
    restart: unless-stopped

networks:
  musafirgo-net:
    driver: bridge
