services:
  itinerary-service:
    build:
      context: ../../musafirgo-itinerary-service
      dockerfile: Dockerfile
    image: musafirgo-itinerary-service:dev
    container_name: itinerary-service
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=${JAVA_OPTS:--XX:+UseG1GC -XX:MaxRAMPercentage=75}
    restart: unless-stopped
    networks:
      - musafirgo-net

networks:
  musafirgo-net:
    driver: bridge
