version: "3.8"

services:
  itinerary-service:
    image: ${ITINERARY_IMAGE:-ghcr.io/musafirgo/musafirgo-itinerary-service:latest}
    container_name: itinerary-service
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=${JAVA_OPTS:--XX:+UseG1GC -XX:MaxRAMPercentage=75}
    restart: unless-stopped
    networks:
      - musafirgo-net

networks:
  musafirgo-net:
    driver: bridge
